/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.io.File;

import com.amazonaws.AmazonServiceException;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.auth.BasicSessionCredentials;
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.internal.StaticCredentialsProvider;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.securitytoken.AWSSecurityTokenService;
import com.amazonaws.services.securitytoken.AWSSecurityTokenServiceAsyncClient;
import com.amazonaws.services.securitytoken.model.AssumeRoleRequest;
import com.amazonaws.services.securitytoken.model.AssumeRoleResult;
import com.amazonaws.services.securitytoken.model.Credentials;

public class App {

    /**
     * example invocation
     * 
     * app.App arn:aws:iam::account-number:role/assume-role-test mysession /path/to/file.txt bucket-name my/prefix/file.txt
     * 
     */

    public static void main(String[] args) {
        String roleToAssume = args[0];
        String roleSessionName = args[1];
        String filePath = args[2];
        String bucketName = args[3];
        String keyName = args[4];
        String profile = args.length == 6 ? args[5] : null;
        AWSCredentialsProvider credsProvider = loadCredentials(true, profile, roleToAssume, roleSessionName);
        System.out.println(credsProvider.getCredentials().getAWSAccessKeyId());
        uploadObject(credsProvider, filePath, bucketName, keyName);
    }

    class AWSStaticCredentials implements AWSCredentialsProvider {

        private AWSCredentials creds;

        public AWSStaticCredentials(AWSCredentials creds) {
            this.creds = creds;
        }

        @Override
        public AWSCredentials getCredentials() {
            return this.creds;
        }

        @Override
        public void refresh() {
            throw new UnsupportedOperationException("Unimplemented method 'refresh'");
        }
        
    }

    private static AWSCredentialsProvider loadCredentials(boolean isLocal, String profile, String roleToAssume, String roleSessionName) {
        final AWSCredentialsProvider credentialsProvider;
        if (isLocal) {
            AWSSecurityTokenService stsClient = new AWSSecurityTokenServiceAsyncClient(
                new ProfileCredentialsProvider(profile));
            
            AssumeRoleRequest assumeRoleRequest = new AssumeRoleRequest().withDurationSeconds(900)
                    .withRoleArn(roleToAssume)
                    .withRoleSessionName("RoleSessionName");

            AssumeRoleResult assumeRoleResult = stsClient.assumeRole(assumeRoleRequest);
            Credentials creds = assumeRoleResult.getCredentials();            

            credentialsProvider = new StaticCredentialsProvider(
                new BasicSessionCredentials(creds.getAccessKeyId(), creds.getSecretAccessKey(), creds.getSessionToken()));
        } else {
            credentialsProvider = new DefaultAWSCredentialsProviderChain();
        }

        return credentialsProvider;
    }

    private static void uploadObject(AWSCredentialsProvider credsProvider, String file_path, String bucket_name, String key_name) {
        System.out.format("Uploading %s to S3 bucket %s...\n", file_path, bucket_name);
        final AmazonS3 s3 = new AmazonS3Client(credsProvider);
        try {
            s3.putObject(bucket_name, key_name, new File(file_path));
        } catch (AmazonServiceException e) {
            System.err.println(e.getErrorMessage());
            System.exit(1);
        }
    }
}

